PREFERENCE_MAPPING = {
    "drinking": "bar OR pub OR nightclub",
    "hiking": "hiking trails OR nature park",
    "museum": "museum OR art gallery",
    "cafe": "cafe OR coffee shop",
    "shopping": "shopping mall OR boutique OR market",
    "sports": "stadium OR sports arena OR gym",
    "dining": "restaurant OR fine dining OR casual dining",
    "nature": "botanical garden OR park OR nature reserve",
    "historical": "historical site OR landmark OR heritage site",
    "entertainment": "theater OR cinema OR concert hall OR comedy club",
    "family": "family friendly OR amusement park OR zoo",
    "romantic": "romantic restaurant OR scenic viewpoint OR love nest",
    "art": "art gallery OR exhibition OR museum",
    "nightlife": "night club OR lounge OR live music",
    "local": "local market OR cultural center OR street food",
    "fitness": "gym OR fitness center OR yoga studio",
    "spa": "spa OR wellness center OR massage parlor",
    "science": "science museum OR planetarium OR discovery center",
    "bookstore": "bookstore OR library",
    "concert": "concert venue OR live music",
    "theater": "theater OR performing arts center",
    "outdoors": "outdoor adventure OR hiking trails OR picnic park",
    "food": "food market OR gourmet food shop OR culinary school",
    "cultural": "cultural center OR heritage site OR folk museum",
    "movies": "movie theatre OR cinema",
    "cinema": "movie theatre OR cinema",
    "music": "live music OR concert hall OR jazz club",
    "exhibition": "exhibition center OR art expo",
    "festival": "festival OR cultural event OR fair",
    "barbecue": "barbecue restaurant OR grill",
    "pub": "pub OR tavern",
    "coastal": "beach OR seaside resort OR coastal park",
    "adventure": "adventure park OR extreme sports center",
    "amusement": "amusement park OR carnival",
    "carnival": "carnival OR fair",
    "lake": "lake resort OR lakeside park OR water sports",
    "river": "river cruise OR river walk OR river park",
    "skiing": "ski resort OR snowboarding",
    "boating": "boating OR yacht charter OR sailing club",
    "camping": "camping ground OR campsite OR outdoor camping",
    "wellness": "wellness center OR spa OR meditation center",
    "food truck": "food truck OR street food vendor",
    "cuisine": "ethnic restaurant OR regional cuisine",
    "bakery": "bakery OR pastry shop OR cake shop",
    "desserts": "dessert shop OR ice cream parlour OR candy store",
    "coffee": "coffee shop OR cafe OR espresso bar",
    "tea": "tea house OR tea room",
    "wine": "wine bar OR vineyard OR wine tasting",
    "cocktail": "cocktail bar OR lounge",
    "deli": "deli OR sandwich shop",
    "bistro": "bistro OR casual dining",
    "park": "public park OR city park OR green space",
    "zoo": "zoo OR wildlife park",
    "aquarium": "aquarium OR marine life center",
    "opera": "opera house OR opera",
    "crafts": "craft market OR artisan shop",
    "farm": "farmers market OR organic farm",
    "scenic": "scenic viewpoint OR lookout point",
    "landscape": "landscape park OR nature reserve",
    "monument": "monument OR memorial",
    "religious": "church OR temple OR mosque OR religious site",
    "safari": "safari park OR wildlife reserve",
    "golf": "golf course OR country club",
    "ice skating": "ice skating rink OR winter sports center",
    "roller skating": "roller skating rink",
    "climbing": "rock climbing gym OR climbing center",
    "biking": "biking trail OR cycling route OR bike park",
    "running": "running track OR marathon route",
    "yoga": "yoga studio OR wellness center",
    "meditation": "meditation center OR retreat",
    "cooking": "cooking class OR culinary school",
    "chocolate": "chocolate shop OR confectionery",
    "beer": "brewery OR beer hall OR craft beer pub",
    "whiskey": "whiskey bar OR distillery",
    "cider": "cider house OR apple orchard",
    "vegan": "vegan restaurant OR plant-based cafe",
    "vegetarian": "vegetarian restaurant OR healthy cafe",
    "sushi": "sushi bar OR Japanese restaurant",
    "steak": "steakhouse OR grill restaurant",
    "seafood": "seafood restaurant OR fish market",
    "pasta": "Italian restaurant OR pasta bar",
    "dessert": "dessert cafe OR pastry shop",
    "ice cream": "ice cream parlor OR gelato shop",
    "sculpture": "sculpture park OR art installation",
    "architecture": "architectural landmark OR modern architecture",
    "literature": "literary cafe OR bookshop",
    "technology": "tech museum OR innovation center",
    "gaming": "arcade OR gaming center OR eSports arena",
    "board games": "board game cafe OR hobby shop",
    "escape room": "escape room OR puzzle adventure",
}


def map_preference(pref: str) -> str:
    """Map a user-friendly preference to a query string."""
    return PREFERENCE_MAPPING.get(pref.lower(), pref)
